services:
  - type: web
    name: dongjin-ai-replacement
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-cloud.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 900 --max-requests 100 --max-requests-jitter 10 --worker-class sync --preload app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TORCH_HOME
        value: /opt/render/project/src/models
    disk:
      name: sam-models
      mountPath: /opt/render/project/src/models
      sizeGB: 5